name: flutter_flavors_boilerplate
description: "A new Flutter project."

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
    # icon pack
  font_awesome_flutter: ^11.0.0
  hugeicons: ^1.1.7
  # phosphoricons_flutter: ^1.0.0
  # for state management
  flutter_bloc: ^9.1.1
  # for annotating state classes
  freezed_annotation: ^3.1.0
  # library for caching loaded network images
  cached_network_image: ^3.4.1
  # to show app information (version, build, name etc)
  package_info_plus: ^10.2.0
  # network apis
  dio: ^5.10.0
  # dependency injection
  get_it: ^9.2.1
  # utils (date formats, time formats, number formats etc.)
  intl: ^0.20.3
  # screen size management
  flutter_screenutil: ^5.9.3
  # animation library
  flutter_animate: ^4.5.2
  # svg asset support library
  flutter_svg: ^2.3.0
  # google font library
  google_fonts: ^8.1.0
  # device info
  device_info_plus: ^13.2.0
  # shared_preferences
  shared_preferences: ^2.5.5
  # lottie animations
  lottie: ^3.5.1
  # url launcher
  url_launcher: ^6.3.2
  # connectivity
  connectivity_plus: ^7.2.0
  # staggered grid view
  flutter_staggered_grid_view: ^0.7.0
  # path provider for internal file system
  path_provider: ^2.1.6
  # flutter in app webview
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  # linting and error analysis
  flutter_lints: ^6.0.0
  # code generation tool
  build_runner: ^2.15.1
  # for state classes
  freezed: ^3.2.5

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/gifs/
    - assets/images/
    - assets/svgs/
    - assets/videos/
